name: Android_CICD

on:
  pull_request:
    branches: [ main ]  # Thực hiện khi có một pull request vào nhánh main
  push:
    branches: [ main ]  # Thực hiện khi có push vào nhánh main

jobs:
  build:
    runs-on: ubuntu-latest  # Chạy trên hệ điều hành Ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Sử dụng phiên bản v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19'  # Phiên bản Java JDK
          distribution: 'temurin'  # Phân phối Java (Temurin)

      - name: Build with Gradle
        run: ./gradlew build  # Lệnh để xây dựng dự án

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3  # Sửa thành v3
        with:
          name: AndroidCICd.apk  # Tên file artifact
          path: app/build/outputs/apk/debug/app-debug.apk  # Đường dẫn tới APK
