name: Android_CICD

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: build/reports/dependency-check-report.html # Đường dẫn tới báo cáo

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AndroidCICd.apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Run Unit Tests
        run: ./gradlew test
